---
kind: Namespace
apiVersion: v1
metadata:
  name: basic-flow-app
---
apiVersion: v1
kind: Service
metadata:
  name: basic-flow-app-service
  namespace: basic-flow-app
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: basic-flow-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-flow-app-deployment
  namespace: basic-flow-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: basic-flow-app
  template:
    metadata:
      labels:
        app: basic-flow-app
    spec:
      containers:
      - name: basic-flow-app-container
        image: acrpromptpromptflow.azurecr.io/basic-flow-image:latest
        env:
        - name: AZURE_OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: aoai-secret
              key: aoai-key
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "1"
            memory: "500Mi"
          requests:
            cpu: "0.5"
            memory: "200Mi"