---
kind: Namespace
apiVersion: v1
metadata:
  name: basic-flow-app
---
apiVersion: v1
kind: Service
metadata:
  name: basic-flow-app-service
  namespace: basic-flow-app
  annotations: 
    azure.workload.identity/client-id: "cd882227-e1c6-4ee6-8be0-771c3000613b"
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: basic-flow-app
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: basic-flow-app-sa
  namespace: basic-flow-app
  annotations: 
    azure.workload.identity/client-id: "cd882227-e1c6-4ee6-8be0-771c3000613b"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-flow-app-deployment
  namespace: basic-flow-app
spec:
  selector:
    matchLabels:
      azure.workload.identity/use: "true" # THIS IS A REQUIRED PROPERTY
      app: basic-flow-app
  template:
    metadata:
      labels:
        app: basic-flow-app
        azure.workload.identity/use: "true" # THIS IS A REQUIRED PROPERTY
    spec:
      serviceAccountName: basic-flow-app-sa
      containers:
      - name: basic-flow-app-container
        image: acrpromptpromptflow.azurecr.io/basic-flow-image:latest
        imagePullPolicy: Always
        env:
        - name: AZURE_OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: aoai-secret
              key: aoai-key
        - name: AZURE_OPENAI_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: aoai-secret
              key: aoai-endpoint
        - name: AZURE_OPENAI_API_VERSION
          valueFrom:
            secretKeyRef:
              name: aoai-secret
              key: aoai-version
        - name: AZURE_OPENAI_DEPLOYMENT
          valueFrom:
            secretKeyRef:
              name: aoai-secret
              key: aoai-deployment
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "0.5"
            memory: "250Mi"
          requests:
            cpu: "0.25"
            memory: "100Mi"