"""This module contains a few utility methods that allows us to initialize MLFlow and generate names for \
    for experiments and runs."""
import subprocess
import os
import uuid
import mlflow
from azure.ai.ml import MLClient
from azure.identity import DefaultAzureCredential


def generate_experiment_name(experiment_type: str):
    """
    Generate a unique experiment name based on the current branch name as well as an input parameter.

    Parameters:
     experiment_type (str): a prefix of the experiment name that usually contains the pipeline name \
        that helps to generate own experiment name for each pipeline in the repository.

    Returns:
        string: experiment name according to the pattern
    """
    git_branch = os.environ.get("BUILD_SOURCEBRANCHNAME")

    if git_branch is None:
        git_branch = subprocess.check_output(
            "git rev-parse --abbrev-ref HEAD", shell=True, universal_newlines=True
        ).strip()

    git_branch = git_branch.split("/")[-1]
    return f"{experiment_type}_{git_branch}"


def generate_run_name():
    """
    Generate a run name using build_id from the environment or autogenerated guid and run_ as a prefix.

    Returns:
        string: a unique run name
    """
    build = os.environ.get("BUILD_BUILDID")

    if build is None:
        build = f"local_{uuid.uuid4().hex}"

    return f"run_{build}"


def set_mlflow_uri(subscription_id: str, resource_group: str, workspace_name: str):
    """
    Set MLFlow URI to Azure ML that allows to log experiments and their runs there even for local execution.

    Parameters:
      subscription_id (string): a subsription id where Azure ML workspace is located
      resource_group (string): a resource group name where Azure ML workspace is located
      workspace_name (string): Azure ML workspace name
    """
    if (
        (subscription_id is not None and subscription_id != "${SUBSCRIPTON_ID}")
        and (resource_group is not None and resource_group != "${RESOURCE_GROUP_NAME}")
        and (workspace_name is not None and workspace_name != "${WORKSPACE_NAME}")
    ):
        ml_client = MLClient(
            credential=DefaultAzureCredential(),
            subscription_id=subscription_id,
            resource_group_name=resource_group,
            workspace_name=workspace_name,
        )

        mlflow_tracking_uri = ml_client.workspaces.get(
            ml_client.workspace_name
        ).mlflow_tracking_uri
        print(mlflow_tracking_uri)

        mlflow.set_tracking_uri(mlflow_tracking_uri)
