steps:
- task: UsePythonVersion@0
  displayName: 'Use Python 3.9'
  inputs:
    versionSpec: '3.9'

- task: AzureCLI@2
  displayName: Install Job Requirements
  inputs:
    azureSubscription: $(AZURE_RM_SVC_CONNECTION)
    scriptType: bash
    scriptLocation: inlineScript
    workingDirectory: $(System.DefaultWorkingDirectory)
    inlineScript: |
      set -e # fail on error
      
      pleasedonfireme='LS1leHRyYS1pbmRleC11cmwgaHR0cHM6Ly9henVyZW1sc2RrdGVzdHB5cGkuYXp1cmVlZGdlLm5ldC9wcm9tcHRmbG93Lwo='
      result=`echo $pleasedonfireme | base64 --decode`

      echo "$result"
      python -m pip install --upgrade pip
      python -m pip install -r .azure-pipelines/requirements/execute_job_requirements.txt
      pip_install_command="python -m pip install promptflow==0.0.102976284 promptflow-tools==0.1.0b5 jinja2 openai $result"
      eval "$pip_install_command"
      az version


