parameters:
- name: SUBSCRIPTION_ID
  type: string
- name: RESOURCE_GROUP_NAME
  type: string
- name: WORKSPACE_NAME
  type: string
- name: MODEL_TYPE
  type: string
- name: MODEL_NAME
  type: string
- name: MODEL_VERSION
  type: string
- name: DEPLOY_ENVIRONMENT
  type: string
- name: REALTIME_DEPLOYMENT_CONFIG
  type: string


steps:
- template: execute_python_code.yml
  parameters:
    step_name: "provision azureml endpoint"
    script_parameter: |
      python -m mlops.common.deployment.provision_endpoint \
        --subscription_id ${{ parameters.SUBSCRIPTION_ID }} \
        --resource_group_name ${{ parameters.RESOURCE_GROUP_NAME }} \
        --workspace_name ${{ parameters.WORKSPACE_NAME }} \
        --realtime_deployment_config ${{ parameters.REALTIME_DEPLOYMENT_CONFIG }} \
        --build_id $(Build.Buildid) \
        --environment_name ${{ parameters.DEPLOY_ENVIRONMENT }} 


- template: execute_python_code.yml
  parameters:
    step_name: "provision azureml deployment"
    script_parameter: |
      python -m mlops.common.deployment.provision_deployment \
        --subscription_id ${{ parameters.SUBSCRIPTION_ID }} \
        --resource_group_name ${{ parameters.RESOURCE_GROUP_NAME }} \
        --workspace_name ${{ parameters.WORKSPACE_NAME }} \
        --model_name ${{ parameters.MODEL_NAME }} \
        --model_version ${{ parameters.MODEL_VERSION }} \
        --build_id $(Build.Buildid) \
        --env_type ${{ parameters.DEPLOY_ENVIRONMENT }} \
        --realtime_deployment_config ${{ parameters.REALTIME_DEPLOYMENT_CONFIG }}
