
parameters:
 - name: exec_environment
   displayName: "Execution Environment"
   default: "pr"
 - name: model_type
   displayName: "type of model to execute"
 - name: devops_container_image
   displayName: acr image
   default: "acrpromptpromptflow.azurecr.io/devops_container_image"
 - name: acr_connection
   displayName: "Azure Container Registry Managed connection"
   default: "acrpromptpromptflow"

stages:
  # Code Validation Stage
  - stage: build_validation
    displayName: 'Validate Code and Evaluate PF Flow'
    jobs:
    - template: build_validation_pipeline.yml
    
    - job: Execute_pf_Pipeline
      displayName: 'Execute Evaluation'
      dependsOn: Build_Validation_Pipeline
      container: devops_container
      steps:
      - template: configure_devops_agent.yml
      - task: AzureCLI@2
        displayName: 'Run Evaluation'
        continueOnError: false
        env:
          SUBSCRIPTION_ID: $(SUBSCRIPTION_ID)
          AOAI_BASE_ENDPOINT: $(AOAI_BASE_ENDPOINT)
          AOAI_API_KEY: $(AOAI_API_KEY)
        inputs: 
          azureSubscription: $(AZURE_RM_SVC_CONNECTION)
          scriptType: bash
          workingDirectory: $(System.DefaultWorkingDirectory)
          scriptLocation: inlineScript
          inlineScript: |
            python -m flows.${{ parameters.model_type }}.evaluate.evaluate \
              --environment_name ${{ parameters.exec_environment }}
