parameters:
 - name: model_type
   displayName: "type of model to execute"

jobs:
- job: Build_Validation_Pipeline
  steps:
  - task: UsePythonVersion@0
    displayName: 'Use Python 3.9'
    inputs:
      versionSpec: '3.9'

  - script: |
      python -m pip install --upgrade pip
      pip install -r devops/pipeline/requirements/build_validation_requirements.txt
    displayName: "Load Python Dependencies"


  - script: |
      pytest test/${{ parameters.model_type }}  --ignore=sandbox/ --junitxml=junit/test-results.xml --cov=. --cov-report=xml
    displayName: 'Run Unit Tests'
    condition: succeededOrFailed()

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: '**/test-*.xml'
      testRunTitle: 'Publish Test Results for Python $(python.version)'

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'