# Azure ML configuration.
aistudio_config:
  subscription_id: ${SUBSCRIPTION_ID}
  resource_group_name: ${RESOURCE_GROUP_NAME}
  project_name: ${PROJECT_NAME}

# Azure OpenAI configuration. 
aoai_config:
  aoai_api_base: ${AOAI_BASE_ENDPOINT}
  aoai_api_type: azure
  aoai_api_version: 2023-07-01-preview
  aoai_api_key: ${AOAI_API_KEY}
  
# flow configurations 
# flow config names are formatted as <flow_name>_<environment>
flow_configs:
  function_basic_flow_pr:
    standard_flow_path: flows/function_basic_flow/standard/flow.flex.yaml
    deployment_name: gpt-35-turbo
    data_path: data/basic_flow_data.jsonl
    eval_data_path: data/basic_flow_eval_data.jsonl
    column_mapping:
      text: ${data.text}
      entity_type: ${data.entity_type}

  class_basic_flow_pr:
    standard_flow_path: flows/class_basic_flow/standard/flow.flex.yaml
    deployment_name: gpt-35-turbo
    data_path: data/basic_flow_data.jsonl
    eval_data_path: data/basic_flow_eval_data.jsonl
    column_mapping:
      text: ${data.text}
      entity_type: ${data.entity_type}

  yaml_basic_flow_pr:
    standard_flow_path: flows/yaml_basic_flow/standard
    deployment_name: gpt-35-turbo
    connection_name: aoai
    data_path: data/basic_flow_data.jsonl
    eval_data_path: data/basic_flow_eval_data.jsonl
    column_mapping:
      text: ${data.text}
      entity_type: ${data.entity_type}

  function_basic_flow_dev:
    standard_flow_path: flows/function_basic_flow/standard/flow.flex.yaml
    deployment_name: gpt-35-turbo
    data_path: data/basic_flow_data.jsonl
    eval_data_path: data/basic_flow_eval_data.jsonl
    column_mapping:
      text: ${data.text}
      entity_type: ${data.entity_type}

  class_basic_flow_dev:
    standard_flow_path: flows/class_basic_flow/standard/flow.flex.yaml
    deployment_name: gpt-35-turbo
    data_path: data/basic_flow_data.jsonl
    eval_data_path: data/basic_flow_eval_data.jsonl
    column_mapping:
      text: ${data.text}
      entity_type: ${data.entity_type}

  yaml_basic_flow_dev:
    standard_flow_path: flows/yaml_basic_flow/standard
    deployment_name: gpt-35-turbo
    data_path: data/basic_flow_data.jsonl
    eval_data_path: data/basic_flow_eval_data.jsonl
    connection_name: aoai
    column_mapping:
      text: ${data.text}
      entity_type: ${data.entity_type}

  plan_and_execute_pr:
    standard_flow_path: flows/plan_and_execute/standard
    deployment_name_gpt35: gpt-35-turbo
    deployment_name_gpt4: gpt-4o
    aoai_api_version: 2023-12-01-preview
    bing_api_key: ${BING_API_KEY}
    bing_endpoint: https://api.bing.microsoft.com/v7.0/search
    connection_name: plan_execute_agent_connection
    data_path: data/plan_and_execute_data.jsonl
    eval_data_path: data/plan_and_execute_eval_data.jsonl
    column_mapping:
      question: ${data.question}

  named_entity_recognition_pr:
    experiment_base_name: named_entity_recognition
    model_base_name: regr
    connection_name: aoai
    deployment_name: gpt-35-turbo
    standard_flow_path: flows/function_basic_flow/standard/flow.flex.yaml
    evaluation_flow_path: flows/named_entity_recognition/evaluation
    data_path: flows/named_entity_recognition/data/data.jsonl
    eval_data_path: flows/named_entity_recognition/data/eval_data.jsonl
    column_mapping:
      text: ${data.text}
      entity_type: ${data.entity_type}
    eval_column_mapping:
      gound_truth: ${data.results}
      entities: ${run.outputs.entities}

  named_entity_recognition_dev:
    experiment_base_name: named_entity_recognition
    model_base_name: regr
    connection_name: aoai
    deployment_name: gpt-35-turbo
    standard_flow_path: flows/named_entity_recognition/standard
    evaluation_flow_path: flows/named_entity_recognition/evaluation
    data_path: flows/named_entity_recognition/data/data.jsonl
    eval_data_path: flows/named_entity_recognition/data/eval_data.jsonl
    realtime_deployment_config: mlops/named_entity_recognition/configs/deployment_config.json
    column_mapping:
      text: ${data.text}
      entity_type: ${data.entity_type}
    eval_column_mapping:
      gound_truth: ${data.results}
      entities: ${run.outputs.entities}
  
  yaml_chat_with_pdf_pr:
    standard_flow_path: flows/chat_with_pdf/standard
    EMBEDDING_MODEL_DEPLOYMENT_NAME: text-embedding-ada-002
    CHAT_MODEL_DEPLOYMENT_NAME: aoai
    connection_name: aoai
    data_path: flows/chat_with_pdf/data/bert-paper-qna.jsonl
    eval_data_path: flows/chat_with_pdf/data/bert-paper-qna-3-line.jsonl
    column_mapping:
      text: ${data.text}
      entity_type: ${data.entity_type}
      pdf_url: ${data.pdf_url}
      chat_history: ${data.chat_history}
      question: ${data.question}
    eval_column_mapping:
      pdf_url: ${data.pdf_url}
      chat_history: ${data.chat_history}
      question: ${data.question}
      gound_truth: ${data.groundtruth}

      
deployment_configs:
  named_entity_recognition_online_dev:
    endpoint_name: named_entity
    endpoint_desc: An online endpoint serving a Promptflow flow
    deployment_desc: prompt flow deployment
    deployment_name: green
    deployment_traffic_allocation: 100
    deployment_vm_size: Standard_F4s_v2
    deployment_instance_count: 1
    deployment_docker_file_path: flows/named_entity_recognition/standard
    environment_variables:
      promptflow_run_mode: serving
