# Azure ML configuration.
aml_config:
  subscription_id: ${SUBSCRIPTION_ID}
  resource_group_name: ${RESOURCE_GROUP_NAME}
  workspace_name: ${WORKSPACE_NAME}
  project_name: ${PROJECT_NAME}

# Azure OpenAI configuration. 
aoai_config:
  aoai_api_base: ${AOAI_BASE_ENDPOINT}
  aoai_api_type: azure
  aoai_api_version: 2023-07-01-preview
  aoai_api_key: ${AOAI_API_KEY}

# Azure Cognitive Service config
acs_config:
  acs_api_base: ${ACS_BASE_ENDPOINT}
  acs_api_version: 2023-07-01-preview
  acs_api_key: ${ACS_API_KEY}

# flow configurations 
# flow config names are formatted as <flow_name>_<environment>
flow_configs:
  named_entity_recognition_pr:
    prompt_flow_config_name: named_entity_recognition
    env_name: pr
    experiment_base_name: named_entity_recognition
    model_base_name: regr
    connection_name: aoai
    deployment_name: gpt-35-turbo
    standard_flow_path: flows/named_entity_recognition/standard
    evaluation_flow_path: flows/named_entity_recognition/evaluation
    data_path: flows/named_entity_recognition/data/data.jsonl
    eval_data_path: flows/named_entity_recognition/data/eval_data.jsonl
    realtime_deployment_config: mlops/named_entity_recognition/configs/deployment_config.json
    column_mapping:
      text: ${data.text}
      entity_type: ${data.entity_type}
    eval_column_mapping:
      gound_truth: ${data.results}
      entities: ${run.outputs.entities}

  named_entity_recognition_dev:
    prompt_flow_config_name: named_entity_recognition
    env_name: dev
    experiment_base_name: named_entity_recognition
    model_base_name: regr
    connection_name: aoai
    deployment_name: gpt-35-turbo
    standard_flow_path: flows/named_entity_recognition/standard
    evaluation_flow_path: flows/named_entity_recognition/evaluation
    data_path: flows/named_entity_recognition/data/data.jsonl
    eval_data_path: flows/named_entity_recognition/data/eval_data.jsonl
    realtime_deployment_config: mlops/named_entity_recognition/configs/deployment_config.json
    column_mapping:
      text: ${data.text}
      entity_type: ${data.entity_type}
    eval_column_mapping:
      gound_truth: ${data.results}
      entities: ${run.outputs.entities}
      
deployment_configs:
  real_time:
    prompt_flow_config_name: named_entity_recognition
    endpoint_name: named_entity
    endpoint_desc: An online endpoint serving a Promptflow flow
    deployment_desc: prompt flow deployment
    deployment_name: green
    deployment_traffic_allocation: 100
    deployment_vm_size: Standard_F4s_v2
    deployment_instance_count: 1
    deployment_docker_file_path: flows/named_entity_recognition/standard
    environment_variables:
      promptflow_run_mode: serving
