---
name: Install Workflow Requirements

description: Installs the required python packages for the workflow.

inputs:
  versionSpec:
    description: "The Python version to use in the environment."
    default: "3.9"

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v1

    - uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.versionSpec }}

    - name: Load Python Dependencies
      shell: bash
      run: |
        set -e # fail on error
        python -m pip install --upgrade pip
        python -m pip install -r .github/requirements/execute_job_requirements.txt
        az version
