name: execute_shell_code

description: execute a shell script given in the inputs

inputs:
  azure_credentials:
    description: "Azure credentials"
    required: true
  script_parameter:
    description: "Command to execute"
    required: true
    default: "python --version"

runs:
  using: composite
  steps:
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ inputs.azure_credentials }}

    - name: Execute code
      shell: bash
      run: |
        ${{inputs.script_parameter}}
