name: execute_shell_code

description: execute a shell script given in the inputs

inputs:
  azure_credentials:
    description: "Azure credentials"
    required: true
  application_insights_connection_string:
    description: "Application Insights connection string"
    required: true
  script_parameter:
    description: "Parameters to execute code"
    required: true
    default: "python --version"

runs:
  using: composite
  steps:
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ inputs.azure_credentials }}

    - name: Checkout
      uses: actions/checkout@v1

    - name: Execute code
      shell: bash
      env:
        APPLICATIONINSIGHTS_CONNECTION_STRING: ${{ inputs.application_insights_connection_string }}
      run: |
        ${{inputs.script_parameter}}
