name: execute_shell_code

description: execute a shell script given in the inputs

inputs:
  client_id: 
    description: "client id of service principal used to authenticate with azure"
    required: true
  tenant_id: 
    description: "tenant id of service principal used to authenticate with azure"
    required: true
  subscription_id:
    description: "subscription id of service principal used to authenticate with azure"
    required: true
  script_parameter:
    description: "Command to execute"
    required: true
    default: "python --version"

runs:
  using: composite
  steps:
    - name: Azure CLI login
      uses: azure/login@v2
      with:
        client_id: ${{ inputs.client_id }}
        tenant_id: ${{ inputs.tenant_id }}
        subscription_id: ${{ inputs.subscription_id }}

    - name: Execute code
      shell: bash
      run: |
        ${{inputs.script_parameter}}
