name: execute_shell_code

description: execute a shell script given in the inputs

inputs:
  azure_credentials:
    description: "Azure credentials"
    required: true
  script_parameter:
    description: "Command to execute"
    required: true
    default: "python --version"

runs:
  using: composite
  steps:
    - name: Azure CLI login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true

    - name: Execute code
      shell: bash
      run: |
        ${{inputs.script_parameter}}
