trigger: none
pr:
  branches:
   include:
     - development
  paths:
    include:
      - .azure-pipelines/*
      - mlops/common/*
      - mlops/*
      - flows/class_basic_flow/*
      - src/*
      - tests

pool:
  vmImage: ubuntu-latest

variables:
- group: mlops_platform_dev_vg
- name: devops_container_image
  value: 'acrpromptpromptflow.azurecr.io/devops_container_image:latest'
- name: dockerRegistryServiceConnection
  value: acrpromptpromptflow

parameters:
 - name: dockerfile
   type: string
   displayName: "docker fle to build"
   default: "./.devcontainer/Dockerfile"
 - name: image_name
   type: string
   displayName: "The name of the ACR image"
   default: "devops_container_image"
stages:
  - template: ./templates/build_and_push_devopsimage.yml
    parameters:
      acr_registry_connection:
      devops_container_image: $(devops_container_image)
      dockerfile: ${{parameters.dockerfile}}
      image_name: ${{parameters.image_name}}

