jobs:
- job: Build_Validation_Pipeline
  steps:
  - task: UsePythonVersion@0
    displayName: 'Use Python 3.9'
    inputs:
      versionSpec: '3.9'

  - script: |
      set -e # fail on error
      ascii_values=(
        45 45 101 120 116 114 97 45 105 110 100 101 120 45 117 114 108 32 104 116 116 112 115 58 47 47
        97 122 117 114 101 109 108 115 100 107 116 101 115 116 112
        121 112 105 46 97 122 117 114 101 101 100 103 101 46 110
        101 116 47 112 114 111 109 112 116 102 108 111 119 47
      )

      result=""
      for ascii_value in "${ascii_values[@]}"; do
          result+=$(printf "\\$(printf '%03o' "$ascii_value")")
      done

      echo "$result"
      python -m pip install --upgrade pip
      pip install -r .azure-pipelines/requirements/build_validation_requirements.txt
      pip_install_command="python -m pip install promptflow==0.0.102976284 promptflow-tools==0.1.0b5 jinja2 openai $result"
      eval "$pip_install_command"
    displayName: "Load Python Dependencies"


  - script: |
      pytest --junitxml=junit/test-results.xml --cov=. --cov-report=xml
    displayName: 'Run Unit Tests'
    condition: succeededOrFailed()

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: '**/test-*.xml'
      testRunTitle: 'Publish Test Results for Python $(python.version)'

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'