jobs:
- job: Build_Validation_Pipeline
  displayName: Validate Code
  steps:
  - template: templates/configure_devops_agent.yml

  - script: |
      flake8 .
    displayName: "Lint with flake8"

  - script: |
      pytest --junitxml=junit/test-results.xml --cov=. --cov-report=xml
    displayName: 'Run Unit Tests'
    condition: succeededOrFailed()

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: '**/test-*.xml'
      testRunTitle: 'Publish Test Results for Python $(python.version)'

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'