trigger: none
pr:
  branches:
   include:
     - development
  paths:
    include:
      - .azure-pipelines/*
      - mlops/common/*
      - mlops/*
      - flows/class_basic_flow/*
      - src/*
      - tests

pool:
  vmImage: ubuntu-latest

variables:
- group: mlops_platform_dev_vg

parameters:
 - name: env_name
   displayName: "Execution Environment"
   default: "pr"
 - name: model_type
   displayName: "model type"
   default: "class_basic_flow"
 - name: acr_registry_connection
   type: string
   displayName: "The name of ACR registry connection"
   default: "acrpromptpromptflow.azurecr.io"
 - name: image_name
   type: string
   displayName: "The name of the ACR image"
   default: "devops_container_image"
stages:
  - template: ./templates/build_and_push_devopsimage.yml
    parameters:
      acr_registry: ${{parameters.acr_registry_connection}}
      dockerfile: ${{parameters.image_name}}
      image_name: ${{parameters.image_name}}
  - template: ./templates/platform_pr_dev_pipeline.yml

    parameters:
      exec_environment: ${{ parameters.env_name }}
      model_type: ${{ parameters.model_type }}
      image_name: ${{image_name}}