
pr: none
trigger:
  branches:
   include:
     - development
  paths:
    include:
      - infra/*


# Azure Pipelines workflow to deploy to Azure using azd
# To configure required secrets and service connection for connecting to Azure, simply run `azd pipeline config --provider azdo`
# Task "Install azd" needs to install setup-azd extension for azdo - https://marketplace.visualstudio.com/items?itemName=ms-azuretools.azd
# See below for alternative task to install azd if you can't install above task in your organization

parameters:
  azureServiceConnection: azconnection

pool:
  vmImage: ubuntu-latest

steps:
  - task: setup-azd@0
    displayName: Install azd

  
  # azd delegate auth to az to use service connection with AzureCLI@2
  - pwsh: |
      azd config set auth.useAzCliAuth "true"
    displayName: Configure AZD to Use AZ CLI Authentication.

  - task: AzureCLI@2
    displayName: Provision Infrastructure
    inputs:
      
      # azconnection is the service connection created by azd. 
      azureSubscription: azconnection
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
         az --version
            az deployment sub create --location=$LOCATION \
            --template-file '${{ github.workspace }}/infra/public_bicep/main.bicep' \
            --parameters resourceGroupName=$RESOURCE_GROUP_NAME location=$LOCATION \
            storageAccount=$STORAGE_ACCT_NAME \
            keyVaultName=$KEYVAULT_NAME \
            appInsightsName=$APPINSIGHTS_NAME \
            containerRegistryName=$CONTAINER_REGISTRY_NAME \
            aiHubName=$AIHUB_NAME \
            aiHubProjectName=$AIHUB_PROJECT_NAME \
            aiServiceName=$AISERVICE_NAME
    env:
      APPINSIGHTS_NAME: $(APPINSIGHTS_NAME)
      CONTAINER_REGISTRY_NAME: $(CONTAINER_REGISTRY_NAME)
      KEYVAULT_NAME: $(KEYVAULT_NAME)
      LOCATION: $(LOCATION)
      RESOURCE_GROUP_NAME: $(RESOURCE_GROUP_NAME)
      STORAGE_ACCT_NAME: $(STORAGE_ACCT_NAME)
      AIHUB_NAME: $(AIHUB_NAME)
      AIHUB_PROJECT_NAME: $(AIHUB_PROJECT_NAME)
      AISERVICE_NAME: $(AISERVICE_NAME)
      AZURE_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
