
parameters:
 - name: exec_environment
   displayName: "Execution Environment"
   default: "dev"
 - name: model_type
   displayName: "type of model to execute"

stages:
  - stage: execute_prompt_evaluation
    displayName: Evaluation Flow
    jobs:
    - job: Execute_pf_Pipeline
      displayName: 'Execute Evaluation'
      steps:
      - template: templates/configure_devops_agent.yml

      - task: AzureCLI@2
        displayName: 'Run Evaluation'
        continueOnError: false
        env:
          SUBSCRIPTION_ID: $(SUBSCRIPTION_ID)
          AOAI_BASE_ENDPOINT: $(AOAI_BASE_ENDPOINT)
          AOAI_API_KEY: $(AOAI_API_KEY)
        inputs: 
          azureSubscription: $(AZURE_RM_SVC_CONNECTION)
          scriptType: bash
          workingDirectory: $(System.DefaultWorkingDirectory)
          scriptLocation: inlineScript
          inlineScript: |
            python -m flows.${{ parameters.model_type }}.evaluate.evaluate \
              --environment_name ${{ parameters.exec_environment }}

  - stage: deploy_prompts
    displayName: Deploy Online Endpoint
    dependsOn: 
    - execute_prompt_evaluation
    jobs:
    - job: deploy_flow
      steps:
      - template: templates/configure_devops_agent.yml
