trigger: none
pr:
  branches:
   include:
     - development
  paths:
    include:
      - flows/*
      - mlops/*
      - .azure-pipelines/*

pool:
  vmImage: ubuntu-latest

variables:
- group: MLOps-DEV-VG-pf

stages:
    - stage: build
      displayName: build_validation
      jobs:
        - template: build_validation_pipeline.yml

    - stage: execute
      displayName: execute_prompt_evaluation
      jobs:
      - job: execute_summarize_evaluation
        steps:
        - script: |
            python -m pip install --upgrade pip
            pip install -r .azure-pipelines/requirements/evaluation_prompt_requirements.txt
          displayName: "Load Python Dependencies"
        - script: |
            python -m mlops.create_connection
          env:
            CONNECTION_NAME: azure_open_ai_connection
            API_KEY: $(API_KEY)
            API_BASE: $(API_BASE)
            API_VERSION: 2023-03-15-preview
            API_TYPE: azure
          displayName: "Initialize PF Connection"
        - script: |
            python -m mlops.evaluate_basic_with_llm
          displayName: "Initialize PF Connection"
