trigger: none
pr: none
  
pool:
  vmImage: ubuntu-latest


variables:
- group: mlops_platform_dev_vg

stages:
- stage: register_datasets
  displayName: register_datasets_stage
  jobs:
  - job: Execute_dataset_registration
    steps:
    - template: templates/configure_devops_agent.yml
    - task: AzureCLI@2
      displayName: 'Run Dataset Registration'
      env:
        SUBSCRIPTION_ID: $(SUBSCRIPTION_ID)
      continueOnError: false
      inputs: 
        azureSubscription: $(AZURE_RM_SVC_CONNECTION)
        scriptType: bash
        workingDirectory: $(System.DefaultWorkingDirectory)
        scriptLocation: inlineScript
        inlineScript: |
          python -m mlops.common.register_data_assets \
            --data_config_path config/data_config.json
