trigger: none
pr:
  branches:
   include:
     - development
  paths:
    include:
      - .azure-pipelines/*
      - mlops/common/*
      - mlops/*
      - flows/yaml_basic_flow/*
      - src/*
      - tests

pool:
  vmImage: ubuntu-latest

variables:
- group: mlops_platform_dev_vg
- name: devops_container_image
  value: 'acrpromptpromptflow.azurecr.io/devops_container_image:latest'
- name: dockerRegistryServiceConnection
  value: acrpromptpromptflow

parameters:
 - name: env_name
   displayName: "Execution Environment"
   default: "pr"
 - name: model_type
   displayName: "model type"
   default: "yaml_basic_flow"
 - name: devops_container_image
   type: string
   displayName: "acr image name"
   required: true
   default: "acrpromptpromptflow.azurecr.io/devops_container_image:latest"

resources:
  containers:
  - container: devops_container
    image: $(devops_container_image)
     
stages:
  - template: ./templates/platform_pr_dev_pipeline.yml
    parameters:
      exec_environment: ${{ parameters.env_name }}
      model_type: ${{ parameters.model_type }}
      acr_connection: $(dockerRegistryServiceConnection)
      devops_container_image: $(devops_container_image)