---
name: Build Validation Workflow

on:
  workflow_call:

env:
  PYTHON_VERSION: "3.9"

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Load Python Dependencies
        shell: bash
        run: |
          set -e
          python -m pip install --upgrade pip
          python -m pip install --upgrade -r .github/requirements/build_validation_requirements.txt

      - name: Run Unit Tests
        shell: bash
        run: |
          pytest --junitxml=junit/test-results.xml --cov=. --cov-report=xml

      - name: Publish Test Results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: "**/test-*.xml"
