name: Pre-build dev container image and Push to ACR

on:
  push:
    branches:
      #- 'development'
      - 'agromova/features/devops_with_container'

env:
  IMAGE_NAME: devops_container_image

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to ACR
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.acr_user_name }}.azurecr.io
          username: ${{ secrets.acr_user_name }}
          password: ${{ secrets.acr_password }}

      - name: Build and push Docker image
        uses: devcontainers/ci@v0.3
        with:
          imageName: ${{ secrets.acr_user_name }}.azurecr.io/${{ env.IMAGE_NAME }}
          cacheFrom: ${{ secrets.acr_user_name }}.azurecr.io/${{ env.IMAGE_NAME }}
          push: always
          runCmd: echo "Build successful"
