name: Pre-build dev container image and Push to ACR

on:
  push:
    branches:
      - 'agromova/features/devops_with_container_v3'
    #   - 'development'

env:
  IMAGE_NAME: devops_container_image
  REGISTRY: ${{ secrets.ACR_REGISTRY }}.azurecr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.azure_credentials }}

      - name: Login to ACR with Azure CLI
        run: |
          az acr login --name ${{ secrets.ACR_REGISTRY }} --username ${{ secrets.ACR_USER_NAME }} --password ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./.devcontainer
          push: true
          tags: ${{ secrets.ACR_REGISTRY }}.azurecr.io/${{ env.IMAGE_NAME }}:latest