---
name: chat_with_pdf PR Workflow

on:
  workflow_call:
    inputs:
      exec_environment:
        type: string
        description: "The environment to run the workflow in"
        required: true
        default: "pr"
      model_type:
        type: string
        description: "The type of model to run the workflow for"
        required: true
        default: "chat_with_pdf"
  pull_request:
    branches:
      - 'development'
    paths:
      - '.github/**'
      - 'mlops/common/**'
      - 'mlops/**'
      - 'flows/chat_with_pdf/**'
      - 'src/**'
      - 'tests/**'

permissions:
  id-token: write
  contents: read
jobs:
  run-pr-workflow:
    uses: ./.github/workflows/platform_pr_dev_workflow.yml
    with:
      exec_environment: ${{ inputs.exec_environment || 'pr' }}
      model_type: ${{ inputs.model_type || 'chat_with_pdf' }}
    secrets:
      subscription_id: ${{ secrets.SUBSCRIPTION_ID }}
      aoai_api_key: ${{ secrets.AOAI_API_KEY }}
      aoai_base_endpoint: ${{ secrets.AOAI_BASE_ENDPOINT }}