---
name: Chat With PDF CI Workflow

on:
  workflow_call:
  push:
    branches:
      - "development"
    paths:
      - '.github/**'
      - 'flows/chat_with_pdf/**'
      - 'src/chat_with_pdf_func_impl/**'

env:
  PROJECT_NAME: ${{ vars.PROJECT_NAME }}
  RESOURCE_GROUP_NAME: ${{ vars.RESOURCE_GROUP_NAME }}
  SUBSCRIPTION_ID: ${{ vars.SUBSCRIPTION_ID }}
  CLIENT_ID: ${{ vars.CLIENT_ID }}
  TENANT_ID: ${{ vars.TENANT_ID }}

permissions:
  id-token: write
  contents: read
jobs:
  run-evaluation-full:
    runs-on: ubuntu-latest
    container:
      image: aipfacr.azurecr.io/devops_container_image:latest
      options: --user root
      credentials:
          username: ${{ secrets.ACR_USER_NAME }}
          password: ${{ secrets.ACR_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Export Secrets 
        uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ toJSON(secrets) }}
          convert: upper
    
      - name: Azure CLI login
        uses: azure/login@v2
        with:
          client-id: ${{ vars.CLIENT_ID }}
          tenant-id: ${{ vars.TENANT_ID }}
          subscription-id: ${{ vars.SUBSCRIPTION_ID }}        

      - name: Execute PF Evaluation Pipeline for Chat With PDF
        shell: bash
        run: |
            python -m flows.chat_with_pdf.evaluate.evaluate \
              --environment_name dev
        env:
          BUILD_BUILDID: "${{ github.run_id }}" # Match the expected name from Azure DevOps pipelines
          BUILD_SOURCEBRANCHNAME: ${{ github.head_ref || github.ref_name }}

  run-function-deployment:
    runs-on: ubuntu-latest
    container:
      image: aipfacr.azurecr.io/devops_container_image:latest
      options: --user root
      credentials:
          username: ${{ secrets.ACR_USER_NAME }}
          password: ${{ secrets.ACR_PASSWORD }}
    needs: run-evaluation-full
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Export Secrets 
        uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ toJSON(secrets) }}
          convert: upper
    
      - name: Azure CLI login
        uses: azure/login@v2
        with:
          client-id: ${{ vars.CLIENT_ID }}
          tenant-id: ${{ vars.TENANT_ID }}
          subscription-id: ${{ vars.SUBSCRIPTION_ID }}   

      - name: Copy Flow Files into Chat With PDF Function Folder
        run: |
            cp -R flows/chat_with_pdf/standard src/chat_with_pdf_func_impl/flow_code
      
      - name: Compress Functions into Zip
        working-directory: ./src/chat_with_pdf_func_impl
        run: |
            zip build.zip * -r

      - name: Execute Azure Functions Deployment
        shell: bash
        run: |
            az functionapp deployment source config-zip -g ${{ vars.RESOURCE_GROUP_NAME }} -n \
            ${{ vars.APP_NAME }} --src 'src/chat_with_pdf_func_impl/build.zip' \
            --build-remote true

            az functionapp config appsettings set --name ${{ vars.APP_NAME }} --resource-group ${{ vars.RESOURCE_GROUP_NAME }} \
            --settings "CHAT_MODEL_DEPLOYMENT_NAME=gpt-35-turbo" \
            "EMBEDDING_MODEL_DEPLOYMENT_NAME=text-embedding-ada-002" \
            "PROMPT_TOKEN_LIMIT=1900" \
            "MAX_COMPLETION_TOKENS=1024" \
            "VERBOSE=true" \
            "CHUNK_SIZE=512" \
            "CHUNK_OVERLAP=64" \
            "AZURE_OPENAI_API_VERSION=2023-07-01-preview" \
            "AZURE_OPENAI_API_KEY=${{ secrets.AOAI_API_KEY }}" \
            "AZURE_OPENAI_ENDPOINT=${{ secrets.AOAI_BASE_ENDPOINT }}"
