---
name: Chat With PDF CI Workflow

on:
  workflow_call:
  push:
    branches:
      - "development"
    paths:
      - '.github/**'
      - 'flows/chat_with_pdf/**'
      - 'src/chat_with_pdf_func_impl/**'

env:
  PYTHON_VERSION: "3.9"
  # Setting an environment variable with the value of a configuration variable
  PROJECT_NAME: ${{ vars.PROJECT_NAME }}
  RESOURCE_GROUP_NAME: ${{ vars.RESOURCE_GROUP_NAME }}

jobs:
  run-evaluation-full:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Export Secrets 
        uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ toJSON(secrets) }}
          convert: upper

      - name: Configure DevOps Agent
        uses: ./.github/actions/configure_devops_agent          

      - name: Execute PF Evaluation Pipeline for Chat With PDF
        uses: ./.github/actions/execute_shell_code
        env:
          BUILD_BUILDID: "${{ github.run_id }}" # Match the expected name from Azure DevOps pipelines
          BUILD_SOURCEBRANCHNAME: ${{ github.head_ref || github.ref_name }}
        with:
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          script_parameter: |
            python -m flows.chat_with_pdf.evaluate.evaluate \
              --environment_name dev

  run-function-deployment:
    runs-on: ubuntu-latest
    needs: run-evaluation-full
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Export Secrets 
        uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ toJSON(secrets) }}
          convert: upper

      - name: Configure DevOps Agent
        uses: ./.github/actions/configure_devops_agent

      - name: Copy Flow Files into Chat With PDF Function Folder
        run: |
            cp -R flows/chat_with_pdf/standard src/chat_with_pdf_func_impl/flow_code
      
      - name: Compress Functions into Zip
        working-directory: ./src/chat_with_pdf_func_impl
        run: |
            zip build.zip * -r

      - name: Execute Azure Functions Deployment
        uses: ./.github/actions/execute_shell_code
        with:
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          script_parameter: |
            az functionapp deployment source config-zip -g ${{ vars.RESOURCE_GROUP_NAME }} -n \
            ${{ vars.APP_NAME }} --src 'src/chat_with_pdf_func_impl/build.zip' \
            --build-remote true

            az functionapp config appsettings set --name ${{ vars.APP_NAME }} --resource-group ${{ vars.RESOURCE_GROUP_NAME }} \
            --settings "CHAT_MODEL_DEPLOYMENT_NAME=gpt-35-turbo" \
            "EMBEDDING_MODEL_DEPLOYMENT_NAME=text-embedding-ada-002" \
            "PROMPT_TOKEN_LIMIT=1900" \
            "MAX_COMPLETION_TOKENS=1024" \
            "VERBOSE=true" \
            "CHUNK_SIZE=512" \
            "CHUNK_OVERLAP=64" \
            "AZURE_OPENAI_API_VERSION=2023-07-01-preview" \
            "AZURE_OPENAI_API_KEY=${{ secrets.AOAI_API_KEY }}" \
            "AZURE_OPENAI_ENDPOINT=${{ secrets.AOAI_BASE_ENDPOINT }}"
