---
name: Named Entity Recognition CI Workflow

on:
  workflow_call:
    inputs:
      exec_environment:
        type: string
        description: "The environment to run the workflow in"
        required: true
        default: "ci"
      model_type:
        type: string
        description: "The type of model to run the workflow for"
        required: true
        default: "named_entity_recognition"
  pull_request:
    branches:
      - "development"

jobs:
  run-ci-workflow:
    uses: ./.github/workflows/platform_ci_dev_workflow.yml
    with:
      exec_environment: ${{ inputs.exec_environment || 'ci' }}
      model_type: ${{ inputs.model_type || 'named_entity_recognition' }}
    secrets:
      subscription_id: ${{ secrets.SUBSCRIPTION_ID }}
      azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
      aoai_api_key: ${{ secrets.AOAI_API_KEY }}
      aoai_base_endpoint: ${{ secrets.AOAI_BASE_ENDPOINT }}
