---
name: plan_and_execute PR Workflow

on:
  workflow_call:
  pull_request:
    branches:
      - 'development'
    paths:
      - '.github/**'
      - 'mlops/common/**'
      - 'mlops/**'
      - 'flows/plan_and_execute/**'
      - 'src/**'
      - 'tests/**'

env:
  # Setting an environment variable with the value of a configuration variable
  PROJECT_NAME: ${{ vars.PROJECT_NAME }}
  RESOURCE_GROUP_NAME: ${{ vars.RESOURCE_GROUP_NAME }}

jobs:
  build-validation:
    name: Build Validation
    uses: ./.github/workflows/build_validation_workflow.yml

  execute-ml-job-pipeline:
    name: Execute PF Job Pipeline
    runs-on: ubuntu-latest
    needs: build-validation
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v1

      - name: Export Secrets 
        uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ toJSON(secrets) }}
          convert: upper

      - name: Configure DevOps Agent
        uses: ./.github/actions/configure_devops_agent

      - name: Execute PF Evaluation Pipeline
        uses: ./.github/actions/execute_shell_code
        env:
          BUILD_BUILDID: "${{ github.run_id }}" # Match the expected name from Azure DevOps pipelines
          BUILD_SOURCEBRANCHNAME: ${{ github.head_ref || github.ref_name }}
        with:
          azure_credentials: ${{ secrets.azure_credentials }}
          script_parameter: |
            python -m flows.plan_and_execute.evaluate.evaluate \
              --environment_name pr
