---
name: plan_and_execute PR Workflow

on:
  workflow_call:
  pull_request:
    branches:
      - 'development'
    paths:
      - '.github/**'
      - 'mlops/common/**'
      - 'mlops/**'
      - 'flows/plan_and_execute/**'
      - 'src/**'
      - 'tests/**'

env:
  # Setting an environment variable with the value of a configuration variable
  PROJECT_NAME: ${{ vars.PROJECT_NAME }}
  RESOURCE_GROUP_NAME: ${{ vars.RESOURCE_GROUP_NAME }}
  SUBSCRIPTION_ID: ${{ vars.SUBSCRIPTION_ID }}
  CLIENT_ID: ${{ vars.CLIENT_ID }}
  TENANT_ID: ${{ vars.TENANT_ID }}

permissions:
  id-token: write
  contents: read
jobs:
  build-validation:
    name: Build Validation
    uses: ./.github/workflows/build_validation_workflow.yml
    secrets:
      ACR_USER_NAME: ${{ secrets.ACR_USER_NAME }}
      ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}

  execute-ml-job-pipeline:
    name: Execute PF Job Pipeline
    runs-on: ubuntu-
    container:
      image: aipfacr.azurecr.io/devops_container_image:latest
      options: --user root
      credentials:
          username: ${{ secrets.ACR_USER_NAME }}
          password: ${{ secrets.ACR_PASSWORD }}
    needs: build-validation
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v1

      - name: Export Secrets 
        uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ toJSON(secrets) }}
          convert: upper
  
      - name: Azure CLI login
        uses: azure/login@v2
        with:
          client-id: ${{ vars.CLIENT_ID }}
          tenant-id: ${{ vars.TENANT_ID }}
          subscription-id: ${{ vars.SUBSCRIPTION_ID }}

      - name: Execute PF Evaluation Pipeline
        shell: bash
        run: |
          python -m flows.plan_and_execute.evaluate.evaluate \
            --environment_name pr
        env:
          BUILD_BUILDID: "${{ github.run_id }}" # Match the expected name from Azure DevOps pipelines
          BUILD_SOURCEBRANCHNAME: ${{ github.head_ref || github.ref_name }}
