---
name: Platform PR Dev Workflow

on:
  workflow_call:
    inputs:
      exec_environment:
        type: string
        description: "Execution Environment"
        required: true
        default: "pr"
      model_type:
        type: string
        description: "type of model to execute"
        required: true
        default: "function_basic_flow"
      acr_registry: 
        type: string
        description: "acr registry name"
        required: true
        default: "acrpromptpromptflow.azurecr.io"
      image_name: 
        type: string
        description: "acr image name"
        required: true
        default: "devops_container_image"
    secrets:
      subscription_id:
        description: "the subscription ID hosting the AML instance."
        required: true
      azure_credentials:
        description: "the credentials to use to authenticate with Azure."
        required: true
      aoai_api_key:
        description: "the API key to use to authenticate with AOAI."
        required: true
      aoai_base_endpoint:
        required: true
        description: "Azure OpenAI base endpoint."
      acr_user_name:
        required: true
        description: "Azure Container Registry user name."
      acr_password:
        required: true
        description: "Azure Container Registry password."
env:
  # Setting an environment variable with the value of a configuration variable
  PROJECT_NAME: ${{ vars.PROJECT_NAME }}
  RESOURCE_GROUP_NAME: ${{ vars.RESOURCE_GROUP_NAME }}


jobs:
  build-validation:
    name: Build Validation
    runs-on: ubuntu-latest
    container: 
      image: ${{ inputs.acr_registry }}/${{ inputs.image_name }}:latest
      credentials:
        username: ${{ secrets.acr_user_name }}
        password: ${{ secrets.acr_password }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run Build Validation Workflow
        uses: ./.github/workflows/build_validation_workflow.yml

  execute-ml-job-pipeline:
    name: Execute PF Job Pipeline
    runs-on: ubuntu-latest
    container: 
      image: ${{ inputs.acr_registry }}/${{ inputs.image_name }}:latest
      credentials:
        username: ${{ secrets.acr_user_name }}
        password: ${{ secrets.acr_password }}
    needs: build-validation
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v1

      - name: Export Secrets 
        uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ toJSON(secrets) }}
          convert: upper

      - name: Configure DevOps Agent
        uses: ./.github/actions/configure_devops_agent

      - name: Execute PF Evaluation Pipeline
        uses: ./.github/actions/execute_shell_code
        env:
          BUILD_BUILDID: "${{ github.run_id }}" # Match the expected name from Azure DevOps pipelines
          BUILD_SOURCEBRANCHNAME: ${{ github.head_ref || github.ref_name }}
        with:
          azure_credentials: ${{ secrets.azure_credentials }}
          script_parameter: |
            python -m flows.${{ inputs.model_type }}.evaluate.evaluate \
              --environment_name ${{ inputs.exec_environment }}
