---
name: Platform PR Dev Workflow

on:
  workflow_call:
    inputs:
      exec_environment:
        type: string
        description: "Execution Environment"
        required: true
        default: "pr"
      model_type:
        type: string
        description: "type of model to execute"
        required: true
        default: "function_basic_flow"
    secrets:
      subscription_id:
        description: "the subscription ID hosting the AML instance."
        required: true
      azure_credentials:
        description: "the credentials to use to authenticate with Azure."
        required: true
      aoai_api_key:
        description: "the API key to use to authenticate with AOAI."
        required: true
      aoai_base_endpoint:
        required: true
        description: "Azure OpenAI base endpoint."
      acr_username:
        required: true
        description: "Azure Container Registry username."
      acr_password:
        required: true
        description: "Azure Container Registry password."
      acr_registry:
        required: true
        description: "Azure Container Registry registry."
env:
  # Setting an environment variable with the value of a configuration variable
  PROJECT_NAME: ${{ vars.PROJECT_NAME }}
  RESOURCE_GROUP_NAME: ${{ vars.RESOURCE_GROUP_NAME }}

jobs:
  build-validation:
    name: Build Validation
    uses: ./.github/workflows/build_validation_workflow.yml

  execute-ml-job-pipeline:
    name: Execute PF Job Pipeline
    runs-on: ubuntu-latest
    needs: build-validation
    steps:
      - name: Docker login
        run: echo "${{ secrets.acr_password }}" | docker login ${{ secrets.acr_registry }}.azurecr.io -u ${{ secrets.acr_password }} --password-stdin

      - name: Pull Docker image
        run: docker pull ${{ secrets.ACR_REGISTRY }}.azurecr.io/devops_container_image:latest

      - name: Checkout Actions
        uses: actions/checkout@v1

      - name: Export Secrets 
        uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ toJSON(secrets) }}
          convert: upper

      - name: Configure DevOps Agent
        uses: ./.github/actions/configure_devops_agent

      - name: Execute PF Evaluation Pipeline
        run: |
          docker run --rm -v $PWD:/workspace - w /workspace ${{ secrets.ACR_REGISTRY }}.azurecr.io/devops_container_image:latest bash -c "
            python -m flows.${{ inputs.model_type }}.evaluate.evaluate \
              --environment_name ${{ inputs.exec_environment }}
          "
        env:
          BUILD_BUILDID: "${{ github.run_id }}" # Match the expected name from Azure DevOps pipelines
          BUILD_SOURCEBRANCHNAME: ${{ github.head_ref || github.ref_name }}
      #   uses: ./.github/actions/execute_shell_code
      #   env:
      #     BUILD_BUILDID: "${{ github.run_id }}" # Match the expected name from Azure DevOps pipelines
      #     BUILD_SOURCEBRANCHNAME: ${{ github.head_ref || github.ref_name }}
      #   with:
      #     azure_credentials: ${{ secrets.azure_credentials }}
      #     script_parameter: |
      #       python -m flows.${{ inputs.model_type }}.evaluate.evaluate \
      #         --environment_name ${{ inputs.exec_environment }}
