name: Register Datasets

on:
  workflow_dispatch:

env:
  PYTHON_VERSION: "3.9"
  PROJECT_NAME: ${{ vars.PROJECT_NAME }}
  RESOURCE_GROUP_NAME: ${{ vars.RESOURCE_GROUP_NAME }}
  SUBSCRIPTION_ID: ${{ vars.SUBSCRIPTION_ID }}
  CLIENT_ID: ${{ vars.CLIENT_ID }}
  TENANT_ID: ${{ vars.TENANT_ID }}

permissions:
  id-token: write
  contents: read
jobs:
  run-registration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Configure DevOps Agent
        uses: ./.github/actions/configure_devops_agent
      - name: Execute Dataset Registration
        uses: ./.github/actions/execute_shell_code
        with:
            client_id: ${{ env.CLIENT_ID }}
            tenant_id: ${{ env.TENANT_ID }}
            subscription_id: ${{ env.SUBSCRIPTION_ID }}
            script_parameter: |
                python -m mlops.common.register_data_assets \
                    --data_config_path config/data_config.json