name: Register Datasets

on:
  workflow_dispatch:

# variables to run the Python script    
env:
  PROJECT_NAME: ${{ vars.PROJECT_NAME }}
  RESOURCE_GROUP_NAME: ${{ vars.RESOURCE_GROUP_NAME }}
  SUBSCRIPTION_ID: ${{ vars.SUBSCRIPTION_ID }}

permissions:
  id-token: write
  contents: read
jobs:
  run-registration:
    runs-on: ubuntu-latest
    container:
      image: aipfacr.azurecr.io/devops_container_image:latest
      options: --user root
      credentials:
          username: ${{ secrets.ACR_USER_NAME }}
          password: ${{ secrets.ACR_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1


      - name: Azure CLI login
        uses: azure/login@v2
        with:
          client-id: ${{ vars.CLIENT_ID }}
          tenant-id: ${{ vars.TENANT_ID }}
          subscription-id: ${{ vars.SUBSCRIPTION_ID }}

      - name: Execute Dataset Registration
        shell: bash
        run: |
          python -m mlops.common.register_data_assets \
            --data_config_path config/data_config.json
