name: Register Datasets

on:
  workflow_dispatch:

# variables to run the Python script    
env:
  PROJECT_NAME: ${{ vars.PROJECT_NAME }}
  RESOURCE_GROUP_NAME: ${{ vars.RESOURCE_GROUP_NAME }}
  SUBSCRIPTION_ID: ${{ vars.SUBSCRIPTION_ID }}

permissions:
  id-token: write
  contents: read
jobs:
  run-registration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
  
      - name: Load Python Dependencies
        shell: bash
        run: |
          set -e # fail on error
          python -m pip install --upgrade pip
          python -m pip install --upgrade -r requirements.txt
          az version

      - name: Azure CLI login
        uses: azure/login@v2
        with:
          client-id: ${{ vars.CLIENT_ID }}
          tenant-id: ${{ vars.TENANT_ID }}
          subscription-id: ${{ vars.SUBSCRIPTION_ID }}

      - name: Execute Dataset Registration
        shell: bash
        run: |
          python -m mlops.common.register_data_assets \
            --data_config_path config/data_config.json
