name: Register Datasets

on:
  workflow_dispatch:

env:
  PYTHON_VERSION: "3.9"
  PROJECT_NAME: ${{ vars.PROJECT_NAME }}
  RESOURCE_GROUP_NAME: ${{ vars.RESOURCE_GROUP_NAME }}

jobs:
  run-registration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Configure DevOps Agent
        uses: ./.github/actions/configure_devops_agent
      - name: Execute Dataset Registration
        uses: ./.github/actions/execute_shell_code
        env: 
            SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        with:
            azure_credentials: ${{ secrets.azure_credentials }}
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            script_parameter: |
                python -m mlops.common.register_data_assets \
                    --data_config_path config/data_config.json