---
name: yaml_basic_flow PR Workflow

on:
  workflow_call:
  pull_request:
    branches:
      - 'development'
    paths:
      - '.github/**'
      - 'mlops/common/**'
      - 'mlops/**'
      - 'flows/yaml_basic_flow/**'
      - 'src/**'
      - 'tests/**'

permissions:
  id-token: write
  contents: read
jobs:
  run-pr-workflow:
    uses: ./.github/workflows/platform_pr_dev_workflow.yml
    with:
      exec_environment: 'pr'
      model_type: 'yaml_basic_flow'
    secrets:
      aoai_api_key: ${{ secrets.AOAI_API_KEY }}
      aoai_base_endpoint: ${{ secrets.AOAI_BASE_ENDPOINT }}
